// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​o​m​e
	 */
	MENU_HOME: string
	/**
	 * W​h​o​ ​a​m​ ​I​?
	 */
	MENU_ABOUT_ME: string
	/**
	 * P​r​o​f​e​s​s​i​o​n​a​l​ ​E​x​p​e​r​i​e​n​c​e
	 */
	MENU_CAREER: string
	/**
	 * P​o​r​t​f​o​l​i​o
	 */
	MENU_PORTFOLIO: string
}

export type TranslationFunctions = {
	/**
	 * Home
	 */
	MENU_HOME: () => LocalizedString
	/**
	 * Who am I?
	 */
	MENU_ABOUT_ME: () => LocalizedString
	/**
	 * Professional Experience
	 */
	MENU_CAREER: () => LocalizedString
	/**
	 * Portfolio
	 */
	MENU_PORTFOLIO: () => LocalizedString
}

export type Formatters = {}
